### ISSUE TITLE
"Error: Call to undefined method LocalFile::getUser()" While I'm uploading the image

### ISSUE THREAD

**Issue by hapugov** [jayktaylor/mw-discord#56]
Hello everyone, I encountered a problem that when the add-on is enabled, uploading pictures to the wiki does not work. If you turn it off, the pictures are quietly unloaded.

```
[7c377a646d61f5d4db582efd] /index.php/%D0%A1%D0%BB%D1%83%D0%B6%D0%B5%D0%B1%D0%BD%D0%B0%D1%8F:%D0%97%D0%B0%D0%B3%D1%80%D1%83%D0%B7%D0%BA%D0%B0 Error: Call to undefined method LocalFile::getUser()

Backtrace:

from /var/www/wiki.exfil.ru/extensions/Discord/src/DiscordHooks.php(261)
#0 /var/www/wiki.exfil.ru/includes/HookContainer/HookContainer.php(338): DiscordHooks::onUploadComplete()
#1 /var/www/wiki.exfil.ru/includes/HookContainer/HookContainer.php(137): MediaWiki\HookContainer\HookContainer->callLegacyHook()
#2 /var/www/wiki.exfil.ru/includes/HookContainer/HookRunner.php(4080): MediaWiki\HookContainer\HookContainer->run()
#3 /var/www/wiki.exfil.ru/includes/upload/UploadBase.php(940): MediaWiki\HookContainer\HookRunner->onUploadComplete()
#4 /var/www/wiki.exfil.ru/includes/specials/SpecialUpload.php(568): UploadBase->performUpload()
#5 /var/www/wiki.exfil.ru/includes/specials/SpecialUpload.php(232): SpecialUpload->processUpload()
#6 /var/www/wiki.exfil.ru/includes/specialpage/SpecialPage.php(701): SpecialUpload->execute()
#7 /var/www/wiki.exfil.ru/includes/specialpage/SpecialPageFactory.php(1475): SpecialPage->run()
#8 /var/www/wiki.exfil.ru/includes/MediaWiki.php(327): MediaWiki\SpecialPage\SpecialPageFactory->executePath()
#9 /var/www/wiki.exfil.ru/includes/MediaWiki.php(923): MediaWiki->performRequest()
#10 /var/www/wiki.exfil.ru/includes/MediaWiki.php(576): MediaWiki->main()
#11 /var/www/wiki.exfil.ru/index.php(50): MediaWiki->run()
#12 /var/www/wiki.exfil.ru/index.php(46): wfIndexMain()
#13 {main}
```

**Comment by MPThLee** [comment]
I think you should update extension. The `getUser` method usage on `onUploadComplete` removed in 96070a653879c63ead3d69e8ce7847d630a422b8
